version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - guiiai
  - Logg
  - onnotice
  - pgvector
  - tiktoken
  - tsquery
  - tsvector
  - unocss
  - xsai
ignoreWords: []
import: []
