packages:
  - packages/*
  - libs/*
  - apps/*
catalog:
  '@xsai-ext/providers-cloud': ^0.2.2
  '@xsai/embed': ^0.2.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - es5-ext
  - esbuild
  - nodejieba
  - sharp
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - websocket
