# Database settings
database:
  # 数据库类型：postgres, pglite, sqlite_vec
  type: postgres
  # PostgreSQL 配置 (当 type: postgres 时使用)
  # 可以使用 url 或分开的字段配置
  # url: postgres://postgres:postgres@localhost:5432/tg_search
  host: localhost
  port: 5433
  user: postgres
  password: '123456'
  database: postgres
  
  # PGlite 和 SQLite+Vector 不需要额外配置
  # 数据库文件会自动创建在 path.storage 目录下
  # PGlite: db.pglite
  # SQLite+Vector: db.sqlite

# Message settings
message:
  # Export settings
  export:
    # Number of messages to fetch in each request
    batchSize: 200
    # Number of concurrent requests
    concurrent: 3
    # Number of retry attempts
    retryTimes: 3
    # Number of retry attempts for takeout session (0 means infinite retries)
    maxTakeoutRetries: 3
  # Database batch settings
  batch:
    # Number of messages to save in each batch
    size: 100

# Path settings
path:
  # Storage path
  storage: ~/.telegram-search

# API settings
api:
  # Telegram API settings
  telegram:
    # Get these values from https://my.telegram.org/apps
    apiId: '611335'
    apiHash: d524b414d21f4d37f08684c1df41ac9c
    phoneNumber: '+1234567890'
    # Optional proxy settings
    # proxy:
    #   ip: ''            # Proxy host (IP or hostname)
    #   port: 0          # Proxy port
    #   MTProxy: false   # Whether it's an MTProxy or a normal Socks proxy
    #   secret: ''       # If using MTProxy, provide a secret
    #   socksType: 5     # If using Socks, choose 4 or 5
    #   timeout: 2       # Timeout (in seconds) for connection
    #   username: ''     # Optional username for proxy auth
    #   password: ''     # Optional password for proxy auth
  # Embedding settings
  embedding:
    # Embedding provider (openai or ollama)
    provider: openai
    # Embedding model
    model: text-embedding-3-small
    # API key for provider
    apiKey: your_openai_api_key
    # Optional, for custom API providers
    apiBase: 'https://api.openai.com/v1'
