name: autofix.ci
on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "14.0"
          env: true

      - name: Prepare node-gyp
        run: | 
          pnpm add node-gyp -w

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run typecheck
      - run: pnpm run lint:fix

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
