name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "14.0"
          env: true

      - name: Prepare node-gyp
        run: | 
          pnpm add node-gyp

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "14.0"
          env: true

      - name: Prepare node-gyp
        run: | 
          pnpm add node-gyp

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

  typecheck:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "14.0"
          env: true

      - name: Prepare node-gyp
        run: | 
          pnpm add node-gyp

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Typecheck
        run: pnpm run typecheck
